export interface User {
  _id: string; // this will be generated by MongoDB
  name: string; // name of the user required
  email: string; // email of the user required and unique
  password: string; // password  of the user required
}
